### ISSUE TITLE
GPU implemenetation

### ISSUE THREAD

**Issue by QuantumDeveloper** [Lin20/isosurface#2]
Hi. do you have any plans to show GPU implementation of the same algorithm? I am asking because this algorithm on CPU is not speedy enough for real time terrain generation, for example.

**Comment by Lin20** [comment]
Yes, definitely. This project will be 100% open-source, and at the end of the day hopefully be broken down into a standalone library that people can use. I'll also be explaining it all in the video series.

**Comment by QuantumDeveloper** [comment]
Great!!! When you will do that?

**Comment by Lin20** [comment]
Check out https://github.com/Lin20/PushingVoxelsForward

**Comment by Lin20** [comment]
I actually thought this issue was opened on that repo at first.

**Comment by QuantumDeveloper** [comment]
Thanks. 
I will follow the updates on your GitHub and youtube channel. 
Hope to see your manifold dual contouring implementation on HLSL or GLSL.

Sorry, I missed your second repo first.
